baseURL = 'https://ciglenecki.github.io/'
languageCode = 'en-us'
title = 'Matej Cigleneƒçki'
theme = 'matej'

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false
    lineNos = false
    guessSyntax = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params]
  [params.profile]
    name = "Matej"
    photo = "/images/profile.jpg"
    description = "triple checking"
    
    [[params.profile.links]]
      name = "GitHub"
      url = "https://github.com/ciglenecki"
      external = true
      
    [[params.profile.links]]
      name = "Email"
      url = "mailto:your.email@example.com"
      external = false
      
    [[params.profile.links]]
      name = "LinkedIn"
      url = "https://linkedin.com/in/yourprofile"
      external = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'